package main

import (
	"strings"
)

// Output is one generated file: where it goes, relative to the repository root, and what is in it.
type Output struct {
	Path string
	Body string
}

// Render produces every file the specification describes, in a stable order.
//
// Stable because the staleness check compares bytes: a map iteration anywhere in here would make
// the generator disagree with itself between runs, and the check would report a difference nobody
// could explain or fix.
func Render(s *Spec) []Output {
	out := make([]Output, 0, len(s.Enums)*2+1)
	for _, e := range s.Enums {
		out = append(out, Output{Path: e.Go.File, Body: renderGo(e)})
	}
	for _, e := range s.Enums {
		out = append(out, Output{Path: e.Dart.File, Body: renderDart(e)})
	}

	// One body, written to every surface that needs it. See Spec.TypeScript for why that is a
	// copy per surface rather than a workspace package, and why two copies cannot drift.
	body := renderTypeScript(s)
	for _, f := range s.TypeScript.Files {
		out = append(out, Output{Path: f, Body: body})
	}
	return out
}

// generatedBy is the first line of every file, in the form `go generate` and every editor and
// review tool recognises: https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source.
//
// Recognised matters more than it looks. GitHub collapses a file whose first line matches this in
// a diff, which is the difference between a review that reads the one line of specification that
// changed and a review that scrolls past nine hundred lines of consequence.
const generatedBy = "Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT."

// regenerateNote is the second half of every header: what to run, and what fails if you do not.
var regenerateNote = []string{
	"",
	"Regenerate with `make codegen`.",
	"",
	"Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in",
	"services/core/cmd/statusgen renders the specification and compares it with what is",
	"committed, so a hand edit here fails `make check` and fails CI — which is the half of",
	"SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.",
}

// numberWords lets a specification say "one of the {{n}}" and stay true when a value is added.
//
// A spelled-out count in prose is a hand-maintained scalar, and Docs/11 §3 records what those do
// here: the `make verify` figure conflicted in four consecutive merges and on three of them no
// value in the conflict was correct. This file is the last place that should carry one, so the
// generator substitutes it.
var numberWords = []string{
	"zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
	"eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
	"nineteen", "twenty",
}

func numberWord(n int) string {
	if n >= 0 && n < len(numberWords) {
		return numberWords[n]
	}
	return itoa(n)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	if neg {
		return "-" + string(b)
	}
	return string(b)
}

// docLines turns a specification doc block into wrapped plain lines, blank lines between
// paragraphs preserved and `{{n}}` substituted.
//
// The caller supplies the comment marker, because the three languages spell one differently and
// wrapping has to account for the width the marker takes.
func docLines(doc string, count, width int) []string {
	doc = strings.ReplaceAll(doc, "{{n}}", numberWord(count))

	var lines []string
	for i, para := range strings.Split(strings.TrimSpace(doc), "\n\n") {
		if i > 0 {
			lines = append(lines, "")
		}
		lines = append(lines, wrap(para, width)...)
	}
	return lines
}

// wrap is a greedy word wrap over text whose newlines are not significant.
//
// The specification's paragraphs are written wrapped at whatever width suited the YAML; the
// languages want their own. Re-flowing rather than preserving means the same paragraph reads the
// same in a Go comment at 96 columns and inside a Dart enum body indented by two.
func wrap(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return []string{""}
	}

	var (
		lines []string
		line  string
	)
	for _, w := range words {
		switch {
		case line == "":
			line = w
		case len(line)+1+len(w) <= width:
			line += " " + w
		default:
			lines = append(lines, line)
			line = w
		}
	}
	return append(lines, line)
}

// comment prefixes wrapped lines with a marker, leaving a blank line as the marker alone rather
// than as trailing whitespace — which gofmt strips, `dart format` strips, and a reviewer should
// never have to look at.
func comment(marker string, lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, l := range lines {
		if l == "" {
			out = append(out, strings.TrimRight(marker, " "))
			continue
		}
		out = append(out, marker+l)
	}
	return out
}

// indent prefixes every non-empty line, for a block that sits inside a body.
func indent(pad string, lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, l := range lines {
		if l == "" {
			out = append(out, "")
			continue
		}
		out = append(out, pad+l)
	}
	return out
}

// camel lower-cases the first letter of an identifier: JobStatus becomes jobStatus.
func camel(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// Every doc block in the specification opens with a predicate phrase rather than a sentence — "a
// live offer awaiting the other party" — and the two functions below are why.
//
// Go's convention is that a doc comment opens with the identifier it documents, so Go renders
// "StatusSubmitted is a live offer awaiting the other party." Dart and TypeScript have no such
// convention and want a sentence, so they capitalise the same phrase. One phrase, written once,
// reads correctly in all three; a sentence written for any one of them reads wrongly in the
// others, and "StatusSubmitted is A live offer" was the first draft of this generator.
//
// Validate refuses a doc that opens with a capital unless the opening word is a name, so the rule
// is enforced rather than remembered.

// withLead prefixes a doc's opening phrase, for Go's identifier-first convention.
func withLead(doc, lead string) string { return lead + strings.TrimSpace(doc) }

// capitalised opens a doc as a sentence, for the languages with no such convention.
func capitalised(doc string) string {
	d := strings.TrimSpace(doc)
	if d == "" {
		return d
	}
	return strings.ToUpper(d[:1]) + d[1:]
}
