// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

import 'package:json_annotation/json_annotation.dart';

/// One of the eight bid states in Docs/02 §4, which is authoritative for the names.
///
/// These eight happen to be single words in sentence case, unlike the job statuses, so storing them
/// unaltered looks like it costs nothing. It is the same rule all the same: the document is the
/// source, and the moment somebody lower-cases one of them the pairing test against ck_bids_status
/// is what says so.
///
/// Whether an offer is still open for either party to act on is deliberately not generated. That
/// predicate is internal/bidding's, for the reason the job transition table is internal/jobs':
/// Docs/07 §3 puts every such decision on the platform, and what a client shows is presentation
/// rather than authority.
enum BidStatus {
  /// An offer the provider is composing and nobody else can see.
  ///
  /// Nothing a client can obtain: there is no endpoint that creates one and none that returns one.
  /// It is here because Docs/02 §4 enumerates it.
  @JsonValue('draft')
  draft,

  /// A live offer awaiting the other party.
  ///
  /// What placing an offer produces, and where revising it leaves the offer. The only status this
  /// platform treats as live.
  @JsonValue('submitted')
  submitted,

  /// An offer that has been answered with a different price or timing.
  ///
  /// Nothing writes it, and SHIP-87 decided that deliberately rather than by omission. Docs/02 §4
  /// lists it beside Superseded and describes the two in almost the same words — one offer
  /// "answered with a different price or timing", the other "displaced by a counter from either
  /// party" — which are the same event seen from its two ends. A platform writing both would be
  /// writing two statuses for one transition, and would then have to say which of them a client
  /// branches on.
  ///
  /// Superseded is the one written, for a reason outside this vocabulary: the bid-closed error code
  /// and the BidNoLongerYours response in contracts/paths/bidding.yaml have both enumerated
  /// "rejected, expired, superseded" as the closed statuses since SHIP-85, and neither names
  /// Countered. The published contract had already made the choice.
  ///
  /// It stays in the list because Docs/02 §4 has it and Docs/10 §3.4 pairs the list with
  /// ck_bids_status in both directions — and because a value omitted from a client's enum decodes
  /// as unknown the day somebody starts writing it. The trigger for writing it would be a ticket
  /// needing to distinguish "displaced because the other party answered" from some other way of
  /// being displaced. There is no other way today.
  @JsonValue('countered')
  countered,

  /// The awarded offer.
  ///
  /// At most one bid per job may hold it, and that is a database guarantee rather than an
  /// application one — a partial unique index in migration 000500, not a check in a handler.
  @JsonValue('accepted')
  accepted,

  /// An offer the customer declined, including every competing bid closed by an award.
  @JsonValue('rejected')
  rejected,

  /// An offer the party who made it took back, before it was accepted.
  @JsonValue('withdrawn')
  withdrawn,

  /// An offer that ran out on its own terms.
  @JsonValue('expired')
  expired,

  /// An offer displaced by a counter from either party.
  ///
  /// The row remains, because Docs/02 §4 keeps the whole chain readable to the customer, the
  /// bidding provider and administrators. It can be neither changed nor answered afterwards, only
  /// read.
  @JsonValue('superseded')
  superseded,

  /// A value this build has never heard of.
  ///
  /// Not one the platform sends: the contract enumerates exactly the values above. It exists
  /// because the alternative to decoding an unrecognised one is throwing on it, and Docs/07 §6 is
  /// built on old builds living on devices indefinitely — a client that crashes rather than
  /// degrades has no over-the-air fix.
  ///
  /// Deliberately last, so that `values` stays in the source document's own order and a screen
  /// grouping by this enumeration gets that order without writing a second list.
  unknown;

  /// What the wire calls this value: lower snake case, per Docs/10 §4.7.
  ///
  /// Present for query parameters and for tests that assert against the published contract, not
  /// because anything renders it.
  String get wireName => switch (this) {
        BidStatus.draft => 'draft',
        BidStatus.submitted => 'submitted',
        BidStatus.countered => 'countered',
        BidStatus.accepted => 'accepted',
        BidStatus.rejected => 'rejected',
        BidStatus.withdrawn => 'withdrawn',
        BidStatus.expired => 'expired',
        BidStatus.superseded => 'superseded',
        BidStatus.unknown => 'unknown',
      };

  /// The value as a person reads it — the exact name Docs/02 §4 uses.
  ///
  /// Not free-form copy. CLAUDE.md requires the document's own names, because a customer reading
  /// one on a screen and support reading it in an audit entry have to be reading about the same
  /// thing.
  String get label => switch (this) {
        BidStatus.draft => 'Draft',
        BidStatus.submitted => 'Submitted',
        BidStatus.countered => 'Countered',
        BidStatus.accepted => 'Accepted',
        BidStatus.rejected => 'Rejected',
        BidStatus.withdrawn => 'Withdrawn',
        BidStatus.expired => 'Expired',
        BidStatus.superseded => 'Superseded',

        // Deliberately not "Unknown", which reads as a fault. The record is fine; this build is
        // old, and saying which is the difference between an update and a support call.
        BidStatus.unknown => 'Not shown by this version',
      };
}
