// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

package bidding

import "slices"

// Status is one of the eight bid states in Docs/02 §4, which is authoritative for the names.
//
// These eight happen to be single words in sentence case, unlike the job statuses, so storing
// them unaltered looks like it costs nothing. It is the same rule all the same: the document is
// the source, and the moment somebody lower-cases one of them the pairing test against
// ck_bids_status is what says so.
//
// Whether an offer is still open for either party to act on is deliberately not generated. That
// predicate is internal/bidding's, for the reason the job transition table is internal/jobs':
// Docs/07 §3 puts every such decision on the platform, and what a client shows is presentation
// rather than authority.
type Status string

const (
	// StatusDraft is an offer the provider is composing and nobody else can see.
	//
	// Nothing a client can obtain: there is no endpoint that creates one and none that returns
	// one. It is here because Docs/02 §4 enumerates it.
	StatusDraft Status = "Draft"

	// StatusSubmitted is a live offer awaiting the other party.
	//
	// What placing an offer produces, and where revising it leaves the offer. The only status
	// this platform treats as live.
	StatusSubmitted Status = "Submitted"

	// StatusCountered is an offer that has been answered with a different price or timing.
	//
	// Nothing writes it, and SHIP-87 decided that deliberately rather than by omission. Docs/02
	// §4 lists it beside Superseded and describes the two in almost the same words — one
	// offer "answered with a different price or timing", the other "displaced by a counter from
	// either party" — which are the same event seen from its two ends. A platform writing both
	// would be writing two statuses for one transition, and would then have to say which of them
	// a client branches on.
	//
	// Superseded is the one written, for a reason outside this vocabulary: the bid-closed error
	// code and the BidNoLongerYours response in contracts/paths/bidding.yaml have both
	// enumerated "rejected, expired, superseded" as the closed statuses since SHIP-85, and
	// neither names Countered. The published contract had already made the choice.
	//
	// It stays in the list because Docs/02 §4 has it and Docs/10 §3.4 pairs the list with
	// ck_bids_status in both directions — and because a value omitted from a client's enum
	// decodes as unknown the day somebody starts writing it. The trigger for writing it would be
	// a ticket needing to distinguish "displaced because the other party answered" from some
	// other way of being displaced. There is no other way today.
	StatusCountered Status = "Countered"

	// StatusAccepted is the awarded offer.
	//
	// At most one bid per job may hold it, and that is a database guarantee rather than an
	// application one — a partial unique index in migration 000500, not a check in a handler.
	StatusAccepted Status = "Accepted"

	// StatusRejected is an offer the customer declined, including every competing bid closed by
	// an award.
	StatusRejected Status = "Rejected"

	// StatusWithdrawn is an offer the party who made it took back, before it was accepted.
	StatusWithdrawn Status = "Withdrawn"

	// StatusExpired is an offer that ran out on its own terms.
	StatusExpired Status = "Expired"

	// StatusSuperseded is an offer displaced by a counter from either party.
	//
	// The row remains, because Docs/02 §4 keeps the whole chain readable to the customer, the
	// bidding provider and administrators. It can be neither changed nor answered afterwards,
	// only read.
	StatusSuperseded Status = "Superseded"
)

// Statuses is every value, in the order Docs/02 §4 lists them.
//
// Ordered rather than a set because that order is the document's own, and because it is what
// the pairing test in services/core/migrations compares against ck_bids_status. Docs/10 §3.4
// requires that pairing for every enumeration and generation does not replace it: this list and
// the constraint are written in different languages, and only a test can hold the two together.
var Statuses = []Status{
	StatusDraft,
	StatusSubmitted,
	StatusCountered,
	StatusAccepted,
	StatusRejected,
	StatusWithdrawn,
	StatusExpired,
	StatusSuperseded,
}

// Valid reports whether v is one of the eight above.
func (v Status) Valid() bool { return slices.Contains(Statuses, v) }

// String is the stored form — Docs/02 §4's own string, which is what the database holds.
func (v Status) String() string { return string(v) }

// Wire is the value as it appears in a response body: lower snake case, per Docs/10 §4.7.
//
// Tabulated rather than derived from the stored form, and that is a change generation earned. A
// hand-written table beside the constants is a second list that can disagree with the first,
// which is why this used to be a transformation; a table produced from the same source as the
// constants cannot disagree with them, and it keeps the published string visible beside the
// value it belongs to rather than behind a rule.
//
// The empty string for an unrecognised value is unreachable through Valid and is not a wire
// form anything may send.
func (v Status) Wire() string {
	switch v {
	case StatusDraft:
		return "draft"
	case StatusSubmitted:
		return "submitted"
	case StatusCountered:
		return "countered"
	case StatusAccepted:
		return "accepted"
	case StatusRejected:
		return "rejected"
	case StatusWithdrawn:
		return "withdrawn"
	case StatusExpired:
		return "expired"
	case StatusSuperseded:
		return "superseded"
	}
	return ""
}

// StatusFromWire is Wire read backwards: the value a client named, or false.
//
// Generated for every enumeration rather than for the ones with a caller today. The argument
// against writing it early was that an untested transformation with no caller is worse than
// none — which was right about a hand-written one and does not survive generation, since this
// is produced from the same source as Wire and round-tripped against it by the generator's own
// tests.
func StatusFromWire(wire string) (Status, bool) {
	for _, known := range Statuses {
		if known.Wire() == wire {
			return known, true
		}
	}
	return "", false
}
