// SHIP-150: the one statement that appends to `audit_log`.
//
// A method on the same unexported [postgresStore] as postgres.go and postgres_auth.go, in a file of
// its own because it is a different subject rather than a different layer (Docs/10 §2.2).
//
// # There is exactly one statement here, and that is the file's whole point
//
// No SELECT, no UPDATE, no DELETE. The triggers in `000003` refuse the last two from any connection,
// so writing one would be a statement that cannot succeed; a *read* could be written and is not,
// because SHIP-165 is the ticket that serves the trail and it will want a query shaped by the
// searches Docs/04 §9 asks for — by actor, by target, by date — rather than whatever this file
// happened to leave behind.
//
// The blank line below keeps this a file note rather than a second package comment.

package admin

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/DulsaraNethmin/Shipper/services/core/internal/db"
)

// auditRow is one `audit_log` row as the store writes it.
//
// Separate from [AuditEntry] because the two are different things: an entry is what a caller means,
// and this is what the column list holds — with the identifier and the instant filled in by
// [Auditor.Record], and the metadata already rendered as JSON. Keeping them apart is what stops a
// caller being able to set either of the two fields it must not choose.
type auditRow struct {
	ID uuid.UUID

	ActorType AuditActorType

	// ActorID is uuid.Nil for a system actor, and is written as NULL.
	ActorID uuid.UUID

	Action     AuditAction
	TargetType string
	TargetID   uuid.UUID

	// Reason is "" where there is none, and is written as NULL. The column is nullable and the
	// distinction is real: an empty string is a reason somebody left blank, NULL is an action
	// that has none.
	Reason string

	// Metadata is already-encoded JSON, never empty — [marshalMetadata] returns `{}` for nothing.
	Metadata string

	CreatedAt time.Time
}

// insertAuditEntry appends one row.
//
// # created_at is named rather than left to the column default
//
// See audit.go's header. The column keeps its `DEFAULT now()` for a writer that never comes through
// Go — the operator at a `psql` prompt, and `scripts/verify/90-admin.sh` — and every write from this
// service supplies the injected clock's instant, so an entry sorts correctly against the session,
// dispute and status-history rows it describes. This is the same decision
// [postgresStore.insertSession] records at greater length, taken again rather than inherited,
// because the two tables' reasons are different: that one has a CHECK comparing an expiry to
// `created_at`, and this one has an ordering that support reads.
//
// # The metadata cast is explicit
//
// `$8::jsonb` rather than relying on inference. The value arrives as a Go string, and without the
// cast PostgreSQL is being handed `text` for a `jsonb` column in a statement whose parameter types
// it is asked to infer — which works until somebody adds a second parameter and the inference
// changes. The cast says what the value is.
//
// No RETURNING. The identifier was generated by the caller and there are no column defaults it needs
// told about — the two that exist, `metadata` and `created_at`, are both supplied.
func (postgresStore) insertAuditEntry(ctx context.Context, r db.Runner, row auditRow) error {
	const q = `
		INSERT INTO audit_log
			(id, actor_type, actor_id, action, target_type, target_id, reason, metadata, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9)`

	// NULL rather than the zero uuid: `ck_audit_log_actor_id` requires NULL for a system actor,
	// and the all-zeroes uuid is a value rather than an absence — it would satisfy nothing and
	// would read as an account somebody could go looking for.
	var actorID any
	if row.ActorID != uuid.Nil {
		actorID = row.ActorID
	}

	var reason any
	if row.Reason != "" {
		reason = row.Reason
	}

	if _, err := r.Exec(ctx, q,
		row.ID, row.ActorType, actorID, row.Action, row.TargetType, row.TargetID,
		reason, row.Metadata, row.CreatedAt,
	); err != nil {
		return fmt.Errorf("admin: recording an audit entry for %s: %w", row.Action, err)
	}
	return nil
}
