// SHIP-162: the two statements behind the internal support history.
//
// Methods on the same unexported [postgresStore] as the rest of this domain's SQL (Docs/10 §2.2).
//
// # `admin_notes` is this domain's own table, so there is no port
//
// Unlike [JobDirectory], which spans `jobs`, `bids` and `job_status_history` and therefore lives in
// cmd/api, this file reads and writes one table created by this domain's own migration block. The
// line postgres_users.go drew is between a statement spanning **two other domains'** tables and one
// spanning none, and this is the clearest case of the second there has been.
//
// # There is no UPDATE and no DELETE here
//
// `000802` does not forbid them the way `000003`'s triggers forbid them on `audit_log`, and its
// header records why the two tables differ — a note is a working record and an operator correcting
// one that names the wrong job is legitimate, while an audit entry holds administrators to account
// and must not be rewritten by anybody. What that means here is that the *service* offers no such
// verb: the shape says append-only, and a ticket that needs an edit adds one deliberately rather
// than finding it already sitting in this file.
//
// The blank line below keeps this a file note rather than a second package comment.

package admin

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/DulsaraNethmin/Shipper/services/core/internal/db"
)

// noteColumns is every column of a note, in the order [scanNote] reads them.
const noteColumns = `id, subject_type, subject_id, author_id, body, created_at`

// insertNote appends one note.
//
// # created_at is named rather than left to the column default
//
// The column keeps its `DEFAULT now()` for a writer that never comes through Go — the operator at a
// `psql` prompt — and every write from this service supplies the injected clock's instant, so a note
// sorts correctly against the audit entry describing it. Docs/11 §9's *one row, one clock*, applied
// across the two rows one action writes; postgres_audit.go records the same decision at greater
// length, and this domain has now paid for getting it wrong once, on `admin_sessions`.
//
// No RETURNING. The identifier was generated by the caller and the only default it might have needed
// telling about is the instant, which is supplied.
func (postgresStore) insertNote(ctx context.Context, r db.Runner, n Note) error {
	const q = `
		INSERT INTO admin_notes (id, subject_type, subject_id, author_id, body, created_at)
		VALUES ($1, $2, $3, $4, $5, $6)`

	if _, err := r.Exec(ctx, q,
		n.ID, n.Subject.String(), n.SubjectID, n.AuthorID, n.Body, n.CreatedAt,
	); err != nil {
		return fmt.Errorf("admin: writing a note on %s %s: %w", n.Subject, n.SubjectID, err)
	}
	return nil
}

// notesFor is every note on one subject, newest first.
//
// # Both halves of the subject are in the predicate, and that is what the index is built for
//
// `idx_admin_notes_subject` is composite on `(subject_type, subject_id, created_at DESC)`. A note is
// always opened from the thing it is about, never listed across subjects, so supplying both halves
// makes this an index scan with the ordering already satisfied rather than a filter and a sort.
//
// **`subject_type` is not redundant beside a UUID.** Identifiers are unique in practice and the
// table has no constraint making them unique *across kinds*; a query on `subject_id` alone would be
// asking the database for a guarantee nothing provides, and would stop using the index the moment a
// second kind was added.
//
// # Not paged, deliberately
//
// See [Notes.For] and `000802`. The ordering is not total — two notes written in the same
// microsecond are in an arbitrary order relative to each other — which is acceptable precisely
// because there is no cursor: a total ordering matters when a client resumes from a position, and
// nothing here resumes.
func (postgresStore) notesFor(
	ctx context.Context,
	r db.Runner,
	subject NoteSubject,
	subjectID uuid.UUID,
) ([]Note, error) {
	const q = `
		SELECT ` + noteColumns + `
		FROM admin_notes
		WHERE subject_type = $1 AND subject_id = $2
		ORDER BY created_at DESC`

	rows, err := r.Query(ctx, q, subject.String(), subjectID)
	if err != nil {
		return nil, fmt.Errorf("admin: reading notes: %w", err)
	}
	defer rows.Close()

	var out []Note
	for rows.Next() {
		note, err := scanNote(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, note)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("admin: reading notes: %w", err)
	}
	return out, nil
}

// scanNote reads one row of [noteColumns].
func scanNote(row interface{ Scan(...any) error }) (Note, error) {
	var n Note
	if err := row.Scan(&n.ID, &n.Subject, &n.SubjectID, &n.AuthorID, &n.Body,
		&n.CreatedAt); err != nil {
		return Note{}, fmt.Errorf("admin: reading a note: %w", err)
	}
	return n, nil
}
