// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

package jobs

import "slices"

// Status is one of the twelve job states in Docs/02 §1, which is authoritative for the names.
//
// The stored form is that document's own string, spaces and sentence case included, because
// Docs/10 §3.4 requires it. The wire form is lower snake case, because Docs/10 §4.7 puts
// every enumeration on the wire that way even where the stored form has spaces — so "En route
// to pickup" reaches a client as en_route_to_pickup.
//
// Status is never a settable field. Every transition passes one guarded server-side function
// (Docs/02 §2, CLAUDE.md), and no request body in this API carries a status: one that arrived
// would be refused as an unknown field rather than quietly ignored. The values below are read,
// compared and displayed. They are not a way to assign one.
//
// Which moves are legal is deliberately not generated. Docs/02 §2's transition table lives in
// internal/jobs and nowhere else, because Docs/07 §3 forbids the device deciding anything —
// the app asks the platform what is permitted, and a copy of the table on the phone would be a
// second authority for a question that has one.
type Status string

const (
	// StatusDraft is a job the customer is still preparing; not visible to providers.
	StatusDraft Status = "Draft"

	// StatusOpen is a job that is published and eligible for bids.
	StatusOpen Status = "Open"

	// StatusNegotiating is a job with one or more active bids or counter-offers, still open to
	// eligible bids.
	//
	// Docs/02 §1 calls this a useful presentation status rather than a closed one: technically
	// the job is still available unless the customer closes it or awards a bid.
	StatusNegotiating Status = "Negotiating"

	// StatusAwarded is a job whose customer has accepted one provider bid; a provider commitment
	// exists.
	StatusAwarded Status = "Awarded"

	// StatusDriverAssigned is a job whose provider has nominated a driver, or self-assigned.
	//
	// Skippable. Docs/02 §2 permits Awarded straight to En route to pickup, because a provider
	// driving the job themselves has nobody to nominate.
	StatusDriverAssigned Status = "Driver assigned"

	// StatusEnRouteToPickup is a driver travelling to the pickup.
	StatusEnRouteToPickup Status = "En route to pickup"

	// StatusPickedUp is goods collected, confirmed by the provider.
	//
	// From here Docs/02 §6.2 makes cancellation a support case rather than a state change: once
	// the goods are in somebody's vehicle the route out is Disputed, and an administrator
	// resolving it.
	StatusPickedUp Status = "Picked up"

	// StatusInTransit is goods being transported.
	//
	// Docs/02 §2 allows the platform to apply this as a presentation change rather than an
	// actor recording it.
	StatusInTransit Status = "In transit"

	// StatusDelivered is a successful delivery recorded by the provider, with its proof.
	//
	// Docs/01 §4.4 requires photo proof or a recorded exception reason, never neither — see
	// the proof exception reasons in this same file.
	StatusDelivered Status = "Delivered"

	// StatusCompleted is a job the customer has confirmed, or whose confirmation window expired
	// without dispute (Docs/02 §6.1).
	//
	// Terminal. Docs/02 §2 offers no move out of it.
	StatusCompleted Status = "Completed"

	// StatusCancelled is a job that ended before completion.
	//
	// Terminal. Docs/02 §2 offers no move out of it.
	StatusCancelled Status = "Cancelled"

	// StatusDisputed is a job with an unresolved issue raised by a customer, provider or
	// administrator.
	//
	// It freezes automatic completion until an administrator resolves it, to Completed or to
	// Cancelled (Docs/02 §3).
	StatusDisputed Status = "Disputed"
)

// Statuses is every value, in the order Docs/02 §1 lists them.
//
// Ordered rather than a set because that order is the document's own, and because it is what
// the pairing test in services/core/migrations compares against ck_jobs_status. Docs/10 §3.4
// requires that pairing for every enumeration and generation does not replace it: this list and
// the constraint are written in different languages, and only a test can hold the two together.
var Statuses = []Status{
	StatusDraft,
	StatusOpen,
	StatusNegotiating,
	StatusAwarded,
	StatusDriverAssigned,
	StatusEnRouteToPickup,
	StatusPickedUp,
	StatusInTransit,
	StatusDelivered,
	StatusCompleted,
	StatusCancelled,
	StatusDisputed,
}

// Valid reports whether v is one of the twelve above.
func (v Status) Valid() bool { return slices.Contains(Statuses, v) }

// String is the stored form — Docs/02 §1's own string, which is what the database holds.
func (v Status) String() string { return string(v) }

// Wire is the value as it appears in a response body: lower snake case, per Docs/10 §4.7.
//
// Tabulated rather than derived from the stored form, and that is a change generation earned. A
// hand-written table beside the constants is a second list that can disagree with the first,
// which is why this used to be a transformation; a table produced from the same source as the
// constants cannot disagree with them, and it keeps the published string visible beside the
// value it belongs to rather than behind a rule.
//
// The empty string for an unrecognised value is unreachable through Valid and is not a wire
// form anything may send.
func (v Status) Wire() string {
	switch v {
	case StatusDraft:
		return "draft"
	case StatusOpen:
		return "open"
	case StatusNegotiating:
		return "negotiating"
	case StatusAwarded:
		return "awarded"
	case StatusDriverAssigned:
		return "driver_assigned"
	case StatusEnRouteToPickup:
		return "en_route_to_pickup"
	case StatusPickedUp:
		return "picked_up"
	case StatusInTransit:
		return "in_transit"
	case StatusDelivered:
		return "delivered"
	case StatusCompleted:
		return "completed"
	case StatusCancelled:
		return "cancelled"
	case StatusDisputed:
		return "disputed"
	}
	return ""
}

// StatusFromWire is Wire read backwards: the value a client named, or false.
//
// Generated for every enumeration rather than for the ones with a caller today. The argument
// against writing it early was that an untested transformation with no caller is worse than
// none — which was right about a hand-written one and does not survive generation, since this
// is produced from the same source as Wire and round-tripped against it by the generator's own
// tests.
func StatusFromWire(wire string) (Status, bool) {
	for _, known := range Statuses {
		if known.Wire() == wire {
			return known, true
		}
	}
	return "", false
}
