// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

package delivery

import "slices"

// ProofExceptionReason is why a recorded milestone carries no photograph.
//
// A closed list, and Docs/01 §4.4 wrote it. The three below are that paragraph's own three,
// and there is deliberately no "other": a reason nobody can group is a moderation queue nobody
// can triage (Docs/04 §5). A driver's own words are not lost by leaving it out — the
// milestone's reason field is optional, 500 characters and one row away, so "the recipient
// asked me not to photograph their door" goes there beside a selected reason rather than
// instead of one.
//
// The exception is not a hole in the rule; it is the other half of it. Docs/01 §4.4 makes
// photo proof mandatory and, in the same paragraph, makes the exception path part of the same
// feature — because what must never happen is a driver standing at a delivery point unable to
// finish the job. An exception is evidence rather than the absence of it: a reason chosen from
// this list, recorded in the same transaction and the same table as the photographs.
//
// The stored form is the wire form here, and that is not an oversight. Job and bid statuses
// store Docs/02's exact strings because a document fixes them; no document fixes these, so a
// second spelling would be a translation table with nothing on the other side of it.
type ProofExceptionReason string

const (
	// ExceptionRecipientObjected is Docs/01 §4.4's first: the recipient objects to being
	// photographed.
	//
	// Listed first because it is the one a driver meets most often.
	ExceptionRecipientObjected ProofExceptionReason = "recipient_objected"

	// ExceptionCameraUnavailable is its second: the camera permission is denied or the hardware
	// is unavailable.
	//
	// This is the one a denied-permission flow offers instead of a dead end.
	ExceptionCameraUnavailable ProofExceptionReason = "camera_unavailable"

	// ExceptionLocationUnsafe is its third: the delivery point is unlit or unsafe to photograph.
	//
	// Listed last because it is the one a driver meets in the dark.
	ExceptionLocationUnsafe ProofExceptionReason = "location_unsafe"
)

// ProofExceptionReasons is every value, in the order Docs/01 §4.4 lists them.
//
// Ordered rather than a set because that order is the document's own, and because it is what
// the pairing test in services/core/migrations compares against ck_proofs_exception_reason.
// Docs/10 §3.4 requires that pairing for every enumeration and generation does not replace it:
// this list and the constraint are written in different languages, and only a test can hold the
// two together.
var ProofExceptionReasons = []ProofExceptionReason{
	ExceptionRecipientObjected,
	ExceptionCameraUnavailable,
	ExceptionLocationUnsafe,
}

// Valid reports whether v is one of the three above.
func (v ProofExceptionReason) Valid() bool { return slices.Contains(ProofExceptionReasons, v) }

// String is the stored form — Docs/01 §4.4's own string, which is what the database holds.
func (v ProofExceptionReason) String() string { return string(v) }

// Wire is the value as it appears in a response body: lower snake case, per Docs/10 §4.7.
//
// Tabulated rather than derived from the stored form, and that is a change generation earned. A
// hand-written table beside the constants is a second list that can disagree with the first,
// which is why this used to be a transformation; a table produced from the same source as the
// constants cannot disagree with them, and it keeps the published string visible beside the
// value it belongs to rather than behind a rule.
//
// The empty string for an unrecognised value is unreachable through Valid and is not a wire
// form anything may send.
func (v ProofExceptionReason) Wire() string {
	switch v {
	case ExceptionRecipientObjected:
		return "recipient_objected"
	case ExceptionCameraUnavailable:
		return "camera_unavailable"
	case ExceptionLocationUnsafe:
		return "location_unsafe"
	}
	return ""
}

// ProofExceptionReasonFromWire is Wire read backwards: the value a client named, or false.
//
// Generated for every enumeration rather than for the ones with a caller today. The argument
// against writing it early was that an untested transformation with no caller is worse than
// none — which was right about a hand-written one and does not survive generation, since this
// is produced from the same source as Wire and round-tripped against it by the generator's own
// tests.
func ProofExceptionReasonFromWire(wire string) (ProofExceptionReason, bool) {
	for _, known := range ProofExceptionReasons {
		if known.Wire() == wire {
			return known, true
		}
	}
	return "", false
}
