// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

import 'package:json_annotation/json_annotation.dart';

/// Why a recorded milestone carries no photograph.
///
/// A closed list, and Docs/01 §4.4 wrote it. The three below are that paragraph's own three, and
/// there is deliberately no "other": a reason nobody can group is a moderation queue nobody can
/// triage (Docs/04 §5). A driver's own words are not lost by leaving it out — the milestone's
/// reason field is optional, 500 characters and one row away, so "the recipient asked me not to
/// photograph their door" goes there beside a selected reason rather than instead of one.
///
/// The exception is not a hole in the rule; it is the other half of it. Docs/01 §4.4 makes photo
/// proof mandatory and, in the same paragraph, makes the exception path part of the same feature
/// — because what must never happen is a driver standing at a delivery point unable to finish the
/// job. An exception is evidence rather than the absence of it: a reason chosen from this list,
/// recorded in the same transaction and the same table as the photographs.
///
/// The stored form is the wire form here, and that is not an oversight. Job and bid statuses store
/// Docs/02's exact strings because a document fixes them; no document fixes these, so a second
/// spelling would be a translation table with nothing on the other side of it.
enum ProofExceptionReason {
  /// Docs/01 §4.4's first: the recipient objects to being photographed.
  ///
  /// Listed first because it is the one a driver meets most often.
  @JsonValue('recipient_objected')
  recipientObjected,

  /// Its second: the camera permission is denied or the hardware is unavailable.
  ///
  /// This is the one a denied-permission flow offers instead of a dead end.
  @JsonValue('camera_unavailable')
  cameraUnavailable,

  /// Its third: the delivery point is unlit or unsafe to photograph.
  ///
  /// Listed last because it is the one a driver meets in the dark.
  @JsonValue('location_unsafe')
  locationUnsafe,

  /// A value this build has never heard of.
  ///
  /// Not one the platform sends: the contract enumerates exactly the values above. It exists
  /// because the alternative to decoding an unrecognised one is throwing on it, and Docs/07 §6 is
  /// built on old builds living on devices indefinitely — a client that crashes rather than
  /// degrades has no over-the-air fix.
  ///
  /// Deliberately last, so that `values` stays in the source document's own order and a screen
  /// grouping by this enumeration gets that order without writing a second list.
  unknown;

  /// What the wire calls this value: lower snake case, per Docs/10 §4.7.
  ///
  /// Present for query parameters and for tests that assert against the published contract, not
  /// because anything renders it.
  String get wireName => switch (this) {
        ProofExceptionReason.recipientObjected => 'recipient_objected',
        ProofExceptionReason.cameraUnavailable => 'camera_unavailable',
        ProofExceptionReason.locationUnsafe => 'location_unsafe',
        ProofExceptionReason.unknown => 'unknown',
      };

  /// The value as a person reads it — the exact name Docs/01 §4.4 uses.
  ///
  /// Not free-form copy. CLAUDE.md requires the document's own names, because a customer reading
  /// one on a screen and support reading it in an audit entry have to be reading about the same
  /// thing.
  String get label => switch (this) {
        ProofExceptionReason.recipientObjected => 'recipient_objected',
        ProofExceptionReason.cameraUnavailable => 'camera_unavailable',
        ProofExceptionReason.locationUnsafe => 'location_unsafe',

        // Deliberately not "Unknown", which reads as a fault. The record is fine; this build is
        // old, and saying which is the difference between an update and a support call.
        ProofExceptionReason.unknown => 'Not shown by this version',
      };
}
