-- Reverses 000505.
--
-- `IF EXISTS`, which is this repository's convention for a down migration and is not decoration
-- here. Numbers are drawn from reserved per-domain blocks rather than in time order
-- (migrations/blocks.go), so a new bidding migration is *below* the version a working database
-- already records — and SHIP-15g's guard prints `make migrate-down n=all && make migrate-up` as the
-- fix. That `down` walks the file list downward from the current version, so **this file runs
-- before its own `up` ever has.** The statement below therefore has to be safe against a schema
-- where it was never applied. 000302, 000407, 000502, 000503, 000504 and 000602 all take the same
-- precaution.
--
-- Dropping the constraint drops its comment with it, so there is nothing to restore the way 000503
-- has to restore a sentence 000501 wrote. The schema without this constraint is the schema before
-- it, entire — which is exactly the state 000501 left behind and this migration ended.
ALTER TABLE bids DROP CONSTRAINT IF EXISTS ck_bids_offer_has_timing;
