// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

import 'package:json_annotation/json_annotation.dart';

/// One of the twelve job states in Docs/02 §1, which is authoritative for the names.
///
/// The stored form is that document's own string, spaces and sentence case included, because
/// Docs/10 §3.4 requires it. The wire form is lower snake case, because Docs/10 §4.7 puts every
/// enumeration on the wire that way even where the stored form has spaces — so "En route to
/// pickup" reaches a client as en_route_to_pickup.
///
/// Status is never a settable field. Every transition passes one guarded server-side function
/// (Docs/02 §2, CLAUDE.md), and no request body in this API carries a status: one that arrived
/// would be refused as an unknown field rather than quietly ignored. The values below are read,
/// compared and displayed. They are not a way to assign one.
///
/// Which moves are legal is deliberately not generated. Docs/02 §2's transition table lives in
/// internal/jobs and nowhere else, because Docs/07 §3 forbids the device deciding anything — the
/// app asks the platform what is permitted, and a copy of the table on the phone would be a second
/// authority for a question that has one.
enum JobStatus {
  /// A job the customer is still preparing; not visible to providers.
  @JsonValue('draft')
  draft,

  /// A job that is published and eligible for bids.
  @JsonValue('open')
  open,

  /// A job with one or more active bids or counter-offers, still open to eligible bids.
  ///
  /// Docs/02 §1 calls this a useful presentation status rather than a closed one: technically the
  /// job is still available unless the customer closes it or awards a bid.
  @JsonValue('negotiating')
  negotiating,

  /// A job whose customer has accepted one provider bid; a provider commitment exists.
  @JsonValue('awarded')
  awarded,

  /// A job whose provider has nominated a driver, or self-assigned.
  ///
  /// Skippable. Docs/02 §2 permits Awarded straight to En route to pickup, because a provider
  /// driving the job themselves has nobody to nominate.
  @JsonValue('driver_assigned')
  driverAssigned,

  /// A driver travelling to the pickup.
  @JsonValue('en_route_to_pickup')
  enRouteToPickup,

  /// Goods collected, confirmed by the provider.
  ///
  /// From here Docs/02 §6.2 makes cancellation a support case rather than a state change: once the
  /// goods are in somebody's vehicle the route out is Disputed, and an administrator resolving it.
  @JsonValue('picked_up')
  pickedUp,

  /// Goods being transported.
  ///
  /// Docs/02 §2 allows the platform to apply this as a presentation change rather than an actor
  /// recording it.
  @JsonValue('in_transit')
  inTransit,

  /// A successful delivery recorded by the provider, with its proof.
  ///
  /// Docs/01 §4.4 requires photo proof or a recorded exception reason, never neither — see the
  /// proof exception reasons in this same file.
  @JsonValue('delivered')
  delivered,

  /// A job the customer has confirmed, or whose confirmation window expired without dispute
  /// (Docs/02 §6.1).
  ///
  /// Terminal. Docs/02 §2 offers no move out of it.
  @JsonValue('completed')
  completed,

  /// A job that ended before completion.
  ///
  /// Terminal. Docs/02 §2 offers no move out of it.
  @JsonValue('cancelled')
  cancelled,

  /// A job with an unresolved issue raised by a customer, provider or administrator.
  ///
  /// It freezes automatic completion until an administrator resolves it, to Completed or to
  /// Cancelled (Docs/02 §3).
  @JsonValue('disputed')
  disputed,

  /// A value this build has never heard of.
  ///
  /// Not one the platform sends: the contract enumerates exactly the values above. It exists
  /// because the alternative to decoding an unrecognised one is throwing on it, and Docs/07 §6 is
  /// built on old builds living on devices indefinitely — a client that crashes rather than
  /// degrades has no over-the-air fix.
  ///
  /// Deliberately last, so that `values` stays in the source document's own order and a screen
  /// grouping by this enumeration gets that order without writing a second list.
  unknown;

  /// What the wire calls this value: lower snake case, per Docs/10 §4.7.
  ///
  /// Present for query parameters and for tests that assert against the published contract, not
  /// because anything renders it.
  String get wireName => switch (this) {
        JobStatus.draft => 'draft',
        JobStatus.open => 'open',
        JobStatus.negotiating => 'negotiating',
        JobStatus.awarded => 'awarded',
        JobStatus.driverAssigned => 'driver_assigned',
        JobStatus.enRouteToPickup => 'en_route_to_pickup',
        JobStatus.pickedUp => 'picked_up',
        JobStatus.inTransit => 'in_transit',
        JobStatus.delivered => 'delivered',
        JobStatus.completed => 'completed',
        JobStatus.cancelled => 'cancelled',
        JobStatus.disputed => 'disputed',
        JobStatus.unknown => 'unknown',
      };

  /// The value as a person reads it — the exact name Docs/02 §1 uses.
  ///
  /// Not free-form copy. CLAUDE.md requires the document's own names, because a customer reading
  /// one on a screen and support reading it in an audit entry have to be reading about the same
  /// thing.
  String get label => switch (this) {
        JobStatus.draft => 'Draft',
        JobStatus.open => 'Open',
        JobStatus.negotiating => 'Negotiating',
        JobStatus.awarded => 'Awarded',
        JobStatus.driverAssigned => 'Driver assigned',
        JobStatus.enRouteToPickup => 'En route to pickup',
        JobStatus.pickedUp => 'Picked up',
        JobStatus.inTransit => 'In transit',
        JobStatus.delivered => 'Delivered',
        JobStatus.completed => 'Completed',
        JobStatus.cancelled => 'Cancelled',
        JobStatus.disputed => 'Disputed',

        // Deliberately not "Unknown", which reads as a fault. The record is fine; this build is
        // old, and saying which is the difference between an update and a support call.
        JobStatus.unknown => 'Not shown by this version',
      };
}
