// Code generated by services/core/cmd/statusgen from contracts/statuses.yaml. DO NOT EDIT.
//
// Regenerate with `make codegen`.
//
// Editing this file by hand does not survive. TestGeneratedFilesAreCurrent in
// services/core/cmd/statusgen renders the specification and compares it with what is
// committed, so a hand edit here fails `make check` and fails CI — which is the half of
// SHIP-56a's acceptance criterion that a regeneration target on its own would not meet.

/**
 * One of the twelve job states in Docs/02 §1, which is authoritative for the names.
 *
 * The stored form is that document's own string, spaces and sentence case included, because Docs/10
 * §3.4 requires it. The wire form is lower snake case, because Docs/10 §4.7 puts every
 * enumeration on the wire that way even where the stored form has spaces — so "En route to
 * pickup" reaches a client as en_route_to_pickup.
 *
 * Status is never a settable field. Every transition passes one guarded server-side function
 * (Docs/02 §2, CLAUDE.md), and no request body in this API carries a status: one that arrived
 * would be refused as an unknown field rather than quietly ignored. The values below are read,
 * compared and displayed. They are not a way to assign one.
 *
 * Which moves are legal is deliberately not generated. Docs/02 §2's transition table lives in
 * internal/jobs and nowhere else, because Docs/07 §3 forbids the device deciding anything — the
 * app asks the platform what is permitted, and a copy of the table on the phone would be a second
 * authority for a question that has one.
 */
export const JobStatus = {
  /**
   * A job the customer is still preparing; not visible to providers.
   */
  Draft: "draft",

  /**
   * A job that is published and eligible for bids.
   */
  Open: "open",

  /**
   * A job with one or more active bids or counter-offers, still open to eligible bids.
   *
   * Docs/02 §1 calls this a useful presentation status rather than a closed one: technically the
   * job is still available unless the customer closes it or awards a bid.
   */
  Negotiating: "negotiating",

  /**
   * A job whose customer has accepted one provider bid; a provider commitment exists.
   */
  Awarded: "awarded",

  /**
   * A job whose provider has nominated a driver, or self-assigned.
   *
   * Skippable. Docs/02 §2 permits Awarded straight to En route to pickup, because a provider
   * driving the job themselves has nobody to nominate.
   */
  DriverAssigned: "driver_assigned",

  /**
   * A driver travelling to the pickup.
   */
  EnRouteToPickup: "en_route_to_pickup",

  /**
   * Goods collected, confirmed by the provider.
   *
   * From here Docs/02 §6.2 makes cancellation a support case rather than a state change: once the
   * goods are in somebody's vehicle the route out is Disputed, and an administrator resolving it.
   */
  PickedUp: "picked_up",

  /**
   * Goods being transported.
   *
   * Docs/02 §2 allows the platform to apply this as a presentation change rather than an actor
   * recording it.
   */
  InTransit: "in_transit",

  /**
   * A successful delivery recorded by the provider, with its proof.
   *
   * Docs/01 §4.4 requires photo proof or a recorded exception reason, never neither — see the
   * proof exception reasons in this same file.
   */
  Delivered: "delivered",

  /**
   * A job the customer has confirmed, or whose confirmation window expired without dispute (Docs/02
   * §6.1).
   *
   * Terminal. Docs/02 §2 offers no move out of it.
   */
  Completed: "completed",

  /**
   * A job that ended before completion.
   *
   * Terminal. Docs/02 §2 offers no move out of it.
   */
  Cancelled: "cancelled",

  /**
   * A job with an unresolved issue raised by a customer, provider or administrator.
   *
   * It freezes automatic completion until an administrator resolves it, to Completed or to
   * Cancelled (Docs/02 §3).
   */
  Disputed: "disputed",
} as const;

/**
 * A value of JobStatus: the wire string, not a numeric member.
 *
 * The union is what makes an unhandled value a type error in a switch, which is the whole reason
 * this file is generated rather than typed as a string.
 */
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];

/**
 * Every value, in the order Docs/02 §1 lists them — which is the order to offer or group them
 * in.
 */
export const jobStatusValues: readonly JobStatus[] = [
  JobStatus.Draft,
  JobStatus.Open,
  JobStatus.Negotiating,
  JobStatus.Awarded,
  JobStatus.DriverAssigned,
  JobStatus.EnRouteToPickup,
  JobStatus.PickedUp,
  JobStatus.InTransit,
  JobStatus.Delivered,
  JobStatus.Completed,
  JobStatus.Cancelled,
  JobStatus.Disputed,
];

/**
 * The value as a person reads it — the exact name Docs/02 §1 uses.
 *
 * Not free-form copy. CLAUDE.md requires the document's own names, because a driver reading one on
 * a page and support reading it in an audit entry have to be reading about the same thing.
 */
export const jobStatusLabels: Readonly<Record<JobStatus, string>> = {
  [JobStatus.Draft]: "Draft",
  [JobStatus.Open]: "Open",
  [JobStatus.Negotiating]: "Negotiating",
  [JobStatus.Awarded]: "Awarded",
  [JobStatus.DriverAssigned]: "Driver assigned",
  [JobStatus.EnRouteToPickup]: "En route to pickup",
  [JobStatus.PickedUp]: "Picked up",
  [JobStatus.InTransit]: "In transit",
  [JobStatus.Delivered]: "Delivered",
  [JobStatus.Completed]: "Completed",
  [JobStatus.Cancelled]: "Cancelled",
  [JobStatus.Disputed]: "Disputed",
};

/**
 * Whether an arbitrary string is one of them, narrowing it to JobStatus when it is.
 *
 * Needed because everything arriving from the API is a string until something checks it, and
 * Docs/07 §6's tolerance of an unrecognised value has to be a decision the page takes rather than
 * a cast that hides it.
 */
export function isJobStatus(value: string): value is JobStatus {
  return (jobStatusValues as readonly string[]).includes(value);
}

/**
 * One of the eight bid states in Docs/02 §4, which is authoritative for the names.
 *
 * These eight happen to be single words in sentence case, unlike the job statuses, so storing them
 * unaltered looks like it costs nothing. It is the same rule all the same: the document is the
 * source, and the moment somebody lower-cases one of them the pairing test against ck_bids_status
 * is what says so.
 *
 * Whether an offer is still open for either party to act on is deliberately not generated. That
 * predicate is internal/bidding's, for the reason the job transition table is internal/jobs':
 * Docs/07 §3 puts every such decision on the platform, and what a client shows is presentation
 * rather than authority.
 */
export const BidStatus = {
  /**
   * An offer the provider is composing and nobody else can see.
   *
   * Nothing a client can obtain: there is no endpoint that creates one and none that returns one.
   * It is here because Docs/02 §4 enumerates it.
   */
  Draft: "draft",

  /**
   * A live offer awaiting the other party.
   *
   * What placing an offer produces, and where revising it leaves the offer. The only status this
   * platform treats as live.
   */
  Submitted: "submitted",

  /**
   * An offer that has been answered with a different price or timing.
   *
   * A retained synonym for Superseded, which is the one the platform writes. That is now Docs/02
   * §4's own position rather than an implementation decision waiting for one.
   *
   * SHIP-87 chose it deliberately rather than by omission. Docs/02 §4 lists Countered beside
   * Superseded and describes the two in almost the same words — one offer "answered with a
   * different price or timing", the other "displaced by a counter from either party" — which are
   * the same event seen from its two ends. A platform writing both would be writing two statuses
   * for one transition, and would then have to say which of them a client branches on.
   *
   * Superseded is the one written, for a reason outside this vocabulary: the bid-closed error code
   * and the BidNoLongerYours response in contracts/paths/bidding.yaml have both enumerated
   * "rejected, expired, superseded" as the closed statuses since SHIP-85, and neither names
   * Countered. The published contract had already made the choice.
   *
   * SHIP-96 closed the question from the other side, which is what turned a report into a decision.
   * Rendering the offer chain to its three audiences, nothing acts on the distinction — so the
   * alternative, giving the two statuses a difference they are actually for, would have cost a
   * ticket to produce a value no audience reads.
   *
   * It stays in the list because Docs/02 §4 has it and Docs/10 §3.4 pairs the list with
   * ck_bids_status in both directions — and because a value omitted from a client's enum decodes
   * as unknown the day somebody starts writing it. The trigger for writing it would be a ticket
   * needing to distinguish "displaced because the other party answered" from some other way of
   * being displaced. There is no other way today.
   */
  Countered: "countered",

  /**
   * The awarded offer.
   *
   * At most one bid per job may hold it, and that is a database guarantee rather than an
   * application one — a partial unique index in migration 000500, not a check in a handler.
   */
  Accepted: "accepted",

  /**
   * An offer the customer declined, including every competing bid closed by an award.
   */
  Rejected: "rejected",

  /**
   * An offer the party who made it took back, before it was accepted.
   */
  Withdrawn: "withdrawn",

  /**
   * An offer that ran out on its own terms.
   */
  Expired: "expired",

  /**
   * An offer displaced by a counter from either party.
   *
   * The row remains, because Docs/02 §4 keeps the whole chain readable to the customer, the
   * bidding provider and administrators. It can be neither changed nor answered afterwards, only
   * read.
   */
  Superseded: "superseded",
} as const;

/**
 * A value of BidStatus: the wire string, not a numeric member.
 *
 * The union is what makes an unhandled value a type error in a switch, which is the whole reason
 * this file is generated rather than typed as a string.
 */
export type BidStatus = (typeof BidStatus)[keyof typeof BidStatus];

/**
 * Every value, in the order Docs/02 §4 lists them — which is the order to offer or group them
 * in.
 */
export const bidStatusValues: readonly BidStatus[] = [
  BidStatus.Draft,
  BidStatus.Submitted,
  BidStatus.Countered,
  BidStatus.Accepted,
  BidStatus.Rejected,
  BidStatus.Withdrawn,
  BidStatus.Expired,
  BidStatus.Superseded,
];

/**
 * The value as a person reads it — the exact name Docs/02 §4 uses.
 *
 * Not free-form copy. CLAUDE.md requires the document's own names, because a driver reading one on
 * a page and support reading it in an audit entry have to be reading about the same thing.
 */
export const bidStatusLabels: Readonly<Record<BidStatus, string>> = {
  [BidStatus.Draft]: "Draft",
  [BidStatus.Submitted]: "Submitted",
  [BidStatus.Countered]: "Countered",
  [BidStatus.Accepted]: "Accepted",
  [BidStatus.Rejected]: "Rejected",
  [BidStatus.Withdrawn]: "Withdrawn",
  [BidStatus.Expired]: "Expired",
  [BidStatus.Superseded]: "Superseded",
};

/**
 * Whether an arbitrary string is one of them, narrowing it to BidStatus when it is.
 *
 * Needed because everything arriving from the API is a string until something checks it, and
 * Docs/07 §6's tolerance of an unrecognised value has to be a decision the page takes rather than
 * a cast that hides it.
 */
export function isBidStatus(value: string): value is BidStatus {
  return (bidStatusValues as readonly string[]).includes(value);
}

/**
 * Why a recorded milestone carries no photograph.
 *
 * A closed list, and Docs/01 §4.4 wrote it. The three below are that paragraph's own three, and
 * there is deliberately no "other": a reason nobody can group is a moderation queue nobody can
 * triage (Docs/04 §5). A driver's own words are not lost by leaving it out — the milestone's
 * reason field is optional, 500 characters and one row away, so "the recipient asked me not to
 * photograph their door" goes there beside a selected reason rather than instead of one.
 *
 * The exception is not a hole in the rule; it is the other half of it. Docs/01 §4.4 makes photo
 * proof mandatory and, in the same paragraph, makes the exception path part of the same feature —
 * because what must never happen is a driver standing at a delivery point unable to finish the job.
 * An exception is evidence rather than the absence of it: a reason chosen from this list, recorded
 * in the same transaction and the same table as the photographs.
 *
 * The stored form is the wire form here, and that is not an oversight. Job and bid statuses store
 * Docs/02's exact strings because a document fixes them; no document fixes these, so a second
 * spelling would be a translation table with nothing on the other side of it.
 */
export const ProofExceptionReason = {
  /**
   * Docs/01 §4.4's first: the recipient objects to being photographed.
   *
   * Listed first because it is the one a driver meets most often.
   */
  RecipientObjected: "recipient_objected",

  /**
   * Its second: the camera permission is denied or the hardware is unavailable.
   *
   * This is the one a denied-permission flow offers instead of a dead end.
   */
  CameraUnavailable: "camera_unavailable",

  /**
   * Its third: the delivery point is unlit or unsafe to photograph.
   *
   * Listed last because it is the one a driver meets in the dark.
   */
  LocationUnsafe: "location_unsafe",
} as const;

/**
 * A value of ProofExceptionReason: the wire string, not a numeric member.
 *
 * The union is what makes an unhandled value a type error in a switch, which is the whole reason
 * this file is generated rather than typed as a string.
 */
export type ProofExceptionReason = (typeof ProofExceptionReason)[keyof typeof ProofExceptionReason];

/**
 * Every value, in the order Docs/01 §4.4 lists them — which is the order to offer or group them
 * in.
 */
export const proofExceptionReasonValues: readonly ProofExceptionReason[] = [
  ProofExceptionReason.RecipientObjected,
  ProofExceptionReason.CameraUnavailable,
  ProofExceptionReason.LocationUnsafe,
];

/**
 * The value as a person reads it — the exact name Docs/01 §4.4 uses.
 *
 * Not free-form copy. CLAUDE.md requires the document's own names, because a driver reading one on
 * a page and support reading it in an audit entry have to be reading about the same thing.
 */
export const proofExceptionReasonLabels: Readonly<Record<ProofExceptionReason, string>> = {
  [ProofExceptionReason.RecipientObjected]: "recipient_objected",
  [ProofExceptionReason.CameraUnavailable]: "camera_unavailable",
  [ProofExceptionReason.LocationUnsafe]: "location_unsafe",
};

/**
 * Whether an arbitrary string is one of them, narrowing it to ProofExceptionReason when it is.
 *
 * Needed because everything arriving from the API is a string until something checks it, and
 * Docs/07 §6's tolerance of an unrecognised value has to be a decision the page takes rather than
 * a cast that hides it.
 */
export function isProofExceptionReason(value: string): value is ProofExceptionReason {
  return (proofExceptionReasonValues as readonly string[]).includes(value);
}
