import 'package:dio/dio.dart';

/// Header names, spelled by the platform rather than by us.
///
/// `Idempotency-Key` matches `httpx.HeaderIdempotencyKey`, `X-Request-Id` matches
/// `httpx.HeaderRequestID`, and the credential header below matches `httpx.HeaderAuthorization`
/// and is spelled by RFC 9110 rather than by us.
///
/// All of them live here rather than beside the code that sets each one. A header name written
/// in two places is a header name that gets corrected in one of them.
abstract final class ApiHeaders {
  static const idempotencyKey = 'Idempotency-Key';
  static const requestId = 'X-Request-Id';

  /// Where the access token travels (SHIP-50).
  static const bearer = 'Authorization'; // spelling:ok — HTTP header name, RFC 9110
}

/// Refuses a state-changing request that carries no `Idempotency-Key`, before it is sent.
///
/// The platform already refuses one with `400 idempotency_key_required` (SHIP-15), so this
/// changes no outcome — it changes *where* the mistake surfaces. A missing key found in
/// Dart names the call site; the same mistake found server-side arrives as a failed request in
/// a log, days later, from a build that is already on somebody's phone.
///
/// It deliberately does **not** generate a key. `Docs/07` §4 has the key generated by the
/// client when the user acts and reused unchanged on every retry — that is the entire
/// mechanism by which a dropped connection cannot duplicate a bid, a milestone, or proof. An
/// interceptor minting a fresh key per attempt would produce something that looks correct,
/// passes every test that does not simulate a retry, and duplicates records in the field.
class IdempotencyInterceptor extends Interceptor {
  const IdempotencyInterceptor();

  static const _stateChanging = <String>{'POST', 'PUT', 'PATCH', 'DELETE'};

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    final method = options.method.toUpperCase();
    final Object? key = options.headers[ApiHeaders.idempotencyKey];

    if (_stateChanging.contains(method) && (key == null || '$key'.isEmpty)) {
      handler.reject(
        DioException(
          requestOptions: options,
          type: DioExceptionType.cancel,
          error: StateError(
            '$method ${options.path} has no ${ApiHeaders.idempotencyKey}. Every '
            'state-changing request carries one (CLAUDE.md, SHIP-15). Generate it where the '
            'user acts and reuse it for every retry of that same action — never per attempt.',
          ),
        ),
      );
      return;
    }

    handler.next(options);
  }
}
